# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ky_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[(b'server', '\u670d\u52a1\u5668'), (b'switch', '\u4ea4\u6362\u673a'), (b'firewall', '\u9632\u706b\u5899')], default=b'server', max_length=48, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u603b\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u603b\u8868',
            },
        ),
    ]
